[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "comic-library"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff.lint]
extend-select = ["I", "B"]

[tool.safety]
policy_file = "none"
full_report = true
output = "json"

[tool.mypy]
python_version = "3.13"
